// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Sun Jan 05 20:32:32 2020

cont cont_inst
(
	.clockcont(clockcont_sig) ,	// input  clockcont_sig
	.clock1(clock1_sig) ,	// input  clock1_sig
	.enable(enable_sig) ,	// input  enable_sig
	.reset(reset_sig) ,	// input  reset_sig
	.reset2(reset2_sig) ,	// input  reset2_sig
	.rps(rps_sig) ,	// input  rps_sig
	.salida(salida_sig) ,	// output [11:0] salida_sig
	.min(min_sig) ,	// output [11:0] min_sig
	.max(max_sig) 	// output [11:0] max_sig
);

